### ISSUE TITLE
Your repository is empty

### ISSUE THREAD

**Issue by israrbacha** [catlab-team/latentclr#1]
Hi, thanks for sharing your nice paper. In your paper, you mention that the code is publicly available but the repository is empty. Is this April fool or something?

**Comment by enisimsar** [comment]
Thanks for your interest. We are currently finishing off a few details of our code and it will be released shortly.

**Comment by thoppe** [comment]
Agreed that it's a nice paper! When you share the code, can you please provide the pretrained networks for disentanglement? 

It seems like it's easy to train it yourself, but it's hard to gauge the memory requirements. The non-linear method you propose only uses the z->W mapping network (for StyleGan) right?
