### ISSUE TITLE
Core idea is the same with previous work [https://arxiv.org/abs/2102.10543]

### ISSUE THREAD

**Issue by mouthful** [catlab-team/latentclr#2]
Hi, 
I think your idea that discovering directions using contrastive learning[https://arxiv.org/pdf/2104.00820.pdf] is almost the same with "Do Generative Models Know Disentanglement? Contrastive Learning is All You Need" https://arxiv.org/abs/2102.10543 on arxiv, which was submitted into arxiv two months ago. 
I think you should talk about it seriously.

**Comment by enisimsar** [comment]
Thanks for bringing this work to our attention, we were not aware of it. Indeed it looks like a concurrent work that uses contrastive learning (however there are many differences between the two works in terms of methodology). We will cover this paper in our related work section (we would also like to compare against this paper in our experimental setup, however, their code is not available yet (release date is given for 5/1 on their GitHub page).
