### ISSUE TITLE
evaluation metrics

### ISSUE THREAD

**Issue by di-mi-ta** [catlab-team/latentclr#3]
Hi, 

This work is interesting!
Did you release the code for evaluation metrics like Rescoring Analysis?

Thanks!

**Comment by enisimsar** [comment]
Hi, 

We used the classifiers proposed in [here](https://github.com/NVlabs/stylegan2) and [list](https://github.com/NVlabs/stylegan2/blob/315ac5494112c94f3af5902d7c492b4dc471d112/metrics/linear_separability.py#L20)
