### ISSUE TITLE
Pre-trained weights

### ISSUE THREAD

**Issue by juancprzs** [catlab-team/latentclr#5]
Hi there,

Thanks for the interesting work. Are you planning on sharing pre-trained weights for the models?

If so, I'd be particularly interested in the weights for StyleGAN2 on FFHQ (all the types of direction models would be great).

Than you!

**Comment by enisimsar** [comment]
Hi @juancprzs,

Thanks for your interest! We have the [demo section](https://github.com/catlab-team/latentclr/tree/main/demo) for the pre-trained weights. The [configs directory](https://github.com/catlab-team/latentclr/blob/main/demo/configs) also contains the JSON files which include the sample directions for the datasets that have the pre-trained weights.

There were some broken links in the repository. We have fixed them.

For visualizing the pre-trained weights and directions, you can simply use [the demo notebook](https://github.com/catlab-team/latentclr/blob/main/demo/Demo.ipynb).
