### ISSUE TITLE
A diverse range of alphas (shift for latent codes Z) does not make changes to the generated images.

### ISSUE THREAD

**Issue by MHVali** [catlab-team/latentclr#6]
Hi,

Thanks for sharing the code and directions. I am doing some experiments with your code and noticed that when I change the alpha from scale 1 to 1000, it doesn't lead to big changes in the generated images towards a direction. Here are the images I get for the "SMILE" direction using "NonlinearConditional" model. Do you know what is the reason for this? The only direction which leads to considerable changes with small shift magnitudes (small alphas) is the "Hair Color" direction. I expected when shifting a latent vector in scale of 1000, the generated images would be useless and are not intelligible.

![Screenshot from 2023-12-08 17-12-33](https://github.com/catlab-team/latentclr/assets/55048021/5dfc6894-bb46-4548-8930-9bc7b59e7b88)
![Screenshot from 2023-12-08 17-11-58](https://github.com/catlab-team/latentclr/assets/55048021/e2bfaffe-78c2-43b7-b175-e7e6d79d0e2a)

For more details, I am using StyleGAN2-FFHQ with "generator.use_w=False" and "generator.truncation=0.5". The reason to turn "use_w" to False is that the StyleGAN2 network doesn't generate an identical image for the same latent code z that I get in my other repositories. Even with "use_W=True" the same thing will happen. Another question; what is "use_w" used for?

Thanks for your response in advance!

**Comment by enisimsar** [comment]
Hello, 

Thanks for your interest in our work. 

Are you using the pre-trained weights that are provided in [link](https://drive.google.com/drive/folders/1DIueVjIEmICS2oZ_kXcf_Ml0MVvyTn04?usp=sharing)?

I am sharing the results from [demo](https://github.com/catlab-team/latentclr/blob/main/demo/Demo.ipynb) for the scaled alphas (in scale of 1000) and large alphas lead undesired outputs, as shown:

![Screenshot 2023-12-12 11 28 09](https://github.com/catlab-team/latentclr/assets/10683524/ad761ad3-5fe1-4fb2-98fe-5bc5ed83666c)


We need more information.

**Comment by MHVali** [comment]
Thanks for your response!
Yes, I used the pretrained models provided in the link along with the prepared config and json files (I followed all instructions in the ReadMe file under demo directory). My main aim is to compare your learned directions (provided in demo directory) with some that I learned using my proposed method. I generated a fixed set of latent vectors z from a Normal distribution and I expect to get the same image outputs (using the same truncation in W space and with alpha=0) when giving them as input to StyleGAN2 in your repository and my own repository. However, it only generates the same images from two repositories for an individual latent vector z when I turn "use_w=False" in the generator. Hence, I put "use_w" to "False" as I am interested to get similar generations for a specific latent vector z and compare my method with yours for specific set of random vectors.

As you mentioned in your paper, you find the directions for StyleGAN2 in Z space (not in W space). Right? So, I don't know what is the functionality of "use_w" parameter. 

However, even when I turn "use_w" to "True", still I have this problem but less. Still I would get minor changes for a large shift like 100. Based on my experience and reading other papers, a really small shift magnitude like alpha=2.5 (in both Z and W spaces) would lead to sensible changes to the output generated image. Any help is highly appreciated!

**Comment by MHVali** [comment]
@enisimsar Could you please try to check your code along your discovered directions to make sure everything is alright with them? I am waiting for your response! Thanks!

**Comment by MHVali** [comment]
I found what is the problem. For StyleGAN2, in the demo code, the variable "z" refers to vectors from W space, not vectors from Z (Normal distribution) space. I was feeding vectors from Normal distribution to the network.
It was better if you could mention what you mean by the variable z in the code :)
